server:
#  port: 8081 #for Android
  port: 8082

spring:
  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/book?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    url: jdbc:mysql://132.232.89.108:3306/book?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  mail:
    protocol: smtp
    host: smtp.qq.com
    username: 397655952@qq.com
    password: trqzegrtgygzbghf
    default-encoding: utf-8
    properties:
      mail:
        port: 465
        smtp:
          auth: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
          starttls:
            enable: true
            required: true

mybatis:
  configuration:
    #配置项：开启下划线到驼峰的自动转换. 作用：将数据库字段根据驼峰规则自动注入到对象属性。
    map-underscore-to-camel-case: true

logging:
  level:
    #打印SQL信息
    com.hehe.mapper: debug
